<?php

    $pubEntries = array(
        "berglyd_olsen:2017" => array(
            "Type"     => "Proceedings",
            "Date"     => "2017-06-19",
            "Title"    => "Data Acquisition and Controls Integration of the AWAKE Experiment at CERN",
            "SubTitle" => "Proceedings of IPAC2017, Copenhagen, Denmark",
            "Authors"  => "Veronica K. Berglyd Olsen (University of Oslo, Oslo, Norway), Jozef J. Batkiewicz,
                           Stephane Deghaye, Spencer J. Gessner, Edda Gschwendtner (CERN, Geneva, Switzerland),
                           Patric Muggli (Max Planck Institute for Physics, Munich, Germany and CERN, Geneva, Switzerland).",
            "URL"      => "http://accelconf.web.cern.ch/AccelConf/ipac2017/doi/JACoW-IPAC2017-TUPIK061.html",
            "PDF"      => "http://accelconf.web.cern.ch/AccelConf/ipac2017/papers/tupik061.pdf",
            "DOI"      => "10.18429/JACoW-IPAC2017-TUPIK061",
            "Contrib"  => 1,
        ),
        "berglyd_olsen:2016" => array(
            "Type"     => "Proceedings",
            "Date"     => "2016-10-11",
            "Title"    => "Loading of Wakefields in a Plasma Accelerator Section Driven by a Self-Modulated Proton Beam",
            "SubTitle" => "Proceedings of NAPAC16, Chicago, IL, USA – w/Contributing Talk",
            "Authors"  => "V. K. Berglyd Olsen, E. Adli (University of Oslo, Oslo, Norway),
                           P. Muggli (Max Planck Institute for Physics, Munich, Germany and CERN, Geneva, Switzerland),
                           J. M. Vieira (Instituto Superior Technico, Lisbon, Portugal)",
            "URL"      => "http://vrws.de/napac2016/html/tua4.htm",
            "PDF"      => "http://vrws.de/napac2016/papers/tua4co03.pdf",
            "Slides"   => "http://vrws.de/napac2016/talks/tua4co03_talk.pdf",
            "Contrib"  => 1,
        ),
        "gschwendtner:2016" => array(
            "Type"     => "Article",
            "Date"     => "2016-09-01",
            "Title"    => "AWAKE, The Advanced Proton Driven Plasma Wakefield Acceleration Experiment at CERN",
            "Journal"  => "Nuclear Instruments and Methods in Physics Research Section A",
            "JrnTopic" => "Accelerators, Spectrometers, Detectors and Associated Equipment",
            "Volume"   => "829",
            "Authors"  => "E. Gschwendtner, E. Adli, L. Amorim, R. Apsimon, R. Assmann, A.-M. Bachmann, F. Batsch,
                           J. Bauche, V.K. Berglyd Olsen, M. Bernardini, R. Bingham, B. Biskup, T. Bohl, C. Bracco,
                           P. N. Burrows, G. Burt, B. Buttenschon, A. Butterworth, A. Caldwell, M. Cascella,
                           E. Chevallay, S. Cipiccia, H. Damerau, L. Deacon, P. Dirksen, S. Doebert, U. Dorda,
                           J. Farmer, V. Fedosseev, E. Feldbaumer, R. Fiorito, R. Fonseca, F. Friebel, A.A. Gorn,
                           O. Grulke, J. Hansen, C. Hessler, W. Hofle, J. Holloway, M. Huther, D. Jaroszynski,
                           L. Jensen, S. Jolly, A. Joulaei, M. Kasim, F. Keeble, Y. Li, S. Liu, N. Lopes, K.V. Lotov,
                           S. Mandry, R. Martorelli, M. Martyanov, S. Mazzoni, O. Mete, V.A. Minakov, J. Mitchell,
                           J. Moody, P. Muggli, Z. Najmudin, P. Norreys, E. Oz, A. Pardons, K. Pepitone, A. Petrenko,
                           G. Plyushchev, A. Pukhov, K. Rieger, H. Ruhl, F. Salveter, N. Savard, J. Schmidt, A. Seryi,
                           E. Shaposhnikova, Z.M. Sheng, P. Sherwood, L. Silva, L. Soby, A.P. Sosedkin, R.I. Spitsyn,
                           R. Trines, P.V. Tuev, M. Turner, V. Verzilov, J. Vieira, H. Vincke, Y. Wei, C.P. Welsch,
                           M. Wing, G. Xia, H. Zhang",
            "URL"      => "http://www.sciencedirect.com/science/article/pii/S0168900216001881",
            "PrePrint" => "http://arxiv.org/abs/1512.05498",
            "DOI"      => "10.1016/j.nima.2016.02.026",
            "Contrib"  => 3,
        ),
        "caldwell:2016" => array(
            "Type"     => "Article",
            "Date"     => "2016-09-01",
            "Title"    => "Path to AWAKE: Evolution of the concept",
            "Journal"  => "Nuclear Instruments and Methods in Physics Research Section A",
            "JrnTopic" => "Accelerators, Spectrometers, Detectors and Associated Equipment",
            "Volume"   => "829",
            "Authors"  => "A. Caldwell, E. Adli, L. Amorim, R. Apsimon, T. Argyropoulos, R. Assmann, A.M. Bachmann,
                           F. Batsch, J. Bauche, V.K. Berglyd Olsen, M. Bernardini, R. Bingham, B. Biskup, T. Bohl,
                           C. Bracco, P.N. Burrows, G. Burt, B. Buttenschon, A. Butterworth, M. Cascella,
                           S. Chattopadhyay, E. Chevallay, S. Cipiccia, H. Damerau, L. Deacon, P. Dirksen, S. Doebert,
                           U. Dorda, E. Elsen, J. Farmer, S. Fartoukh, V. Fedosseev, E. Feldbaumer, R. Fiorito,
                           R. Fonseca, F. Friebel, G. Geschonke, B. Goddard, A.A. Gorn, O. Grulke, E. Gschwendtner,
                           J. Hansen, C. Hessler, S. Hillenbrand, W. Hofle, J. Holloway, C. Huang, M. Huther,
                           D. Jaroszynski, L. Jensen, S. Jolly, A. Joulaei, M. Kasim, F. Keeble, R. Kersevan, N. Kumar,
                           Y. Li, S. Liu, N. Lopes, K.V. Lotov, W. Lu, J. Machacek, S. Mandry, I. Martin, R. Martorelli,
                           M. Martyanov, S. Mazzoni, M. Meddahi, L. Merminga, O. Mete, V.A. Minakov, J. Mitchell,
                           J. Moody, A.S. Muller, Z. Najmudin, T.C.Q. Noakes, P. Norreys, J. Osterhoff, E. Oz,
                           A. Pardons, K. Pepitone, A. Petrenko, G. Plyushchev, J. Pozimski, A. Pukhov, O. Reimann,
                           K. Rieger, S. Roesler, H. Ruhl, T. Rusnak, F. Salveter, N. Savard, J. Schmidt,
                           H. von der Schmitt, A. Seryi, E. Shaposhnikova, Z.M. Sheng, P. Sherwood, L. Silva, F. Simon,
                           L. Soby, A.P. Sosedkin, R.I. Spitsyn, T. Tajima, R. Tarkeshian, H. Timko, R. Trines,
                           T. Tueckmantel, P.V. Tuev, M. Turner, F. Velotti, V. Verzilov, J. Vieira, H. Vincke, Y. Wei,
                           C.P. Welsch, M. Wing, G. Xia, V. Yakimenko, H. Zhang, F. Zimmermann",
            "URL"      => "http://www.sciencedirect.com/science/article/pii/S0168900215016307",
            "PrePrint" => "http://arxiv.org/abs/1511.09032",
            "DOI"      => "10.1016/j.nima.2015.12.050",
            "Contrib"  => 3,
        ),
        "adli:2016" => array(
            "Type"     => "Article",
            "Date"     => "2016-09-01",
            "Title"    => "Progress of plasma wakefield self-modulation experiments at FACET",
            "Journal"  => "Nuclear Instruments and Methods in Physics Research Section A",
            "JrnTopic" => "Accelerators, Spectrometers, Detectors and Associated Equipment",
            "Volume"   => "829",
            "Authors"  => "E. Adli, V.K. Berglyd Olsen, C.A. Lindstrøm, P. Muggli, O. Reimann, J.M. Vieira,
                           L.D. Amorim, C.I. Clarke, S.J. Gessner, S.Z. Green, M.J. Hogan, M.D. Litos, B.D. O׳Shea,
                           V. Yakimenko, C. Clayton, K.A. Marsh, W.B. Mori, C. Joshi, N. Vafaei-Najafabadi,
                           O. Williams",
            "URL"      => "http://www.sciencedirect.com/science/article/pii/S0168900216002515",
            "DOI"      => "10.1016/j.nima.2016.02.075",
            "Contrib"  => 2,
        ),
        "muggli:2015" => array(
            "Type"     => "Proceedings",
            "Date"     => "2015-05-08",
            "Title"    => "Measuring the Self-modulation Instability of Electron and Positron Bunches in Plasmas",
            "SubTitle" => "Proceedings of IPAC2015, Richmond, Virginia, USA",
            "Authors"  => "P. Muggli, O. Reimann (MPI-P, München, Germany), E. Adli,
                           V.K. Berglyd Olsen (University of Oslo, Oslo, Norway), J. Allen, S.J. Gessner, S.Z. Green,
                           M.J. Hogan, M.D. Litos (SLAC, Menlo Park, California, USA),
                           L.D. Amorim (IST, Lisboa, Portugal), G. Andonian, C. Joshi, K.A. Marsh, W.B. Mori,
                           B.D. O'Shea, N. Vafaei-Najafabadi, O. Williams (UCLA, Los Angeles, California, USA),
                           N.C. Lopes, L.O. Silva, J. Vieira (Instituto Superior Tecnico, Lisbon, Portugal)",
            "URL"      => "http://inspirehep.net/record/1417872",
            "PDF"      => "https://jacowfs.jlab.org/conf/proceedings/IPAC2015/papers/wepwa008.pdf",
            "Contrib"  => 3,
        ),
        "berglyd_olsen:2015" => array(
            "Type"     => "Proceedings",
            "Date"     => "2015-05-08",
            "Title"    => "Loading of a plasma-wakefield accelerator section driven by a self-modulated proton bunch",
            "SubTitle" => "Proceedings of IPAC2015, Richmond, Virginia, USA",
            "Authors"  => "Veronica K. Berglyd Olsen, Erik Adli (University of Oslo, Oslo),
                           Patric Muggli (MPI, Muenchen), Ligia Diana Amorim,
                           Jorge Miguel Vieira (Instituto Superior Tecnico, Lisbon)",
            "URL"      => "http://inspirehep.net/record/1417886",
            "PDF"      => "https://jacowfs.jlab.org/conf/proceedings/IPAC2015/papers/wepwa026.pdf",
            "Contrib"  => 1,
        ),
        "muggli:2014" => array(
            "Type"     => "Proceedings",
            "Date"     => "2014-06-17",
            "Title"    => "Electron Bunch Self-modulation in Long Plasmas at SLAC FACET",
            "SubTitle" => "Proceedings of IPAC2014, Dresden, Germany",
            "Authors"  => "Patric Muggli, Olaf Reimann (MPI, Muenchen), Ligia Diana Amorim, Nelson Carreira Lopes,
                           Jorge Miguel Vieira (Instituto Superior Tecnico, Lisbon), Spencer Jake Gessner, Mark Hogan,
                           Selina Zhao Li, Michael Dennis Litos (SLAC, Menlo Park, California), Chan Joshi,
                           Kenneth Marsh, Warren Mori, Navid Vafaei-Najafabadi (UCLA, Los Angeles, California),
                           Erik Adli, Veronica K. Berglyd Olsen (University of Oslo, Oslo)",
            "URL"      => "https://inspirehep.net/record/1313831",
            "PDF"      => "http://jacow.org/IPAC2014/papers/tupme050.pdf",
            "Contrib"  => 3,
        ),
        "muggli:2014-1" => array(
            "Type"     => "Proceedings",
            "Date"     => "2014-05-25",
            "Title"    => "Self-modulation of ultra-relativistic SLAC electron and positron bunches",
            "SubTitle" => "2014 IEEE 41st International Conference on Plasma Sciences, Washington DC, USA",
            "Authors"  => "P. Muggli, O. Reimann, J. Vieira, N. Lopes, L.D. Amorim, L. Silva, S. Gessner, M.J. Hogan,
                           S. Li, M. Litos, N. Vafaei-Najafabadi, C. Joshi, W. Mori, K. Marsh, E. Adli, V.K.B. Olsen,
                           Y. Fang",
            "URL"      => "http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7012243",
            "DOI"      => "10.1109/PLASMA.2014.7012243",
            "Contrib"  => 3,
        ),
        "berglyd_olsen:2012" => array(
            "Type"     => "Thesis",
            "Date"     => "2012-12-03",
            "Title"    => "Full Configuration Interaction Simulation of Quantum Dots",
            "SubTitle" => "Thesis submitted for the degree of Master of Science, University of Oslo",
            "Authors"  => "Veronica K. Berglyd Olsen, University of Oslo.
                           Thesis advisor: Morten Hjorth-Jensen, University of Oslo and Michigan State University.",
            "URL"      => "https://www.duo.uio.no/handle/123456789/34217",
            "PDF"      => "https://www.duo.uio.no/bitstream/handle/10852/34217/vkb-olsen.pdf",
            "Contrib"  => 1,
        ),
    );

?>
