<?php

    $pubEntries = array(
        "berglyd_olsen:2019" => array(
            "Type"     => "Thesis",
            "Date"     => "2019-02-25",
            "Title"    => "Beam Loading in a Proton Driven Plasma Wakefield Accelerator",
            "Journal"  => "Dissertation Presented for the Degree of PhD in Physics",
            "Authors"  => "Veronica K. Berglyd Olsen, University of Oslo.
                           Thesis Advisors: Erik Adli (University of Oslo, Oslo, Norway),
                           Patric Muggli (Max Planck Institute for Physics, Munich, Germany and CERN, Geneva, Switzerland).",
            "URL"      => "http://cds.cern.ch/record/2655446",
            "PDF"      => "http://cds.cern.ch/record/2655446/files/CERN-THESIS-2018-343.pdf",
            "Slides"   => "http://vkbo.net/files/phd-defence.pdf",
            "Contrib"  => 1,
        ),
        "turner:2019" => array(
            "Type"     => "Article",
            "Date"     => "2019-02-08",
            "Title"    => "Experimental Observation of Plasma Wakefield Growth Driven by the Seeded<br>Self-Modulation of a Proton Bunch",
            "Journal"  => "Physical Review Letters",
            "Authors"  => "M. Turner, E. Adli, A. Ahuja, O. Apsimon, R. Apsimon, A.-M. Bachmann, M. Barros Marin, D. Barrientos,
                           F. Batsch, J. Batkiewicz, J. Bauche, V. K. Berglyd Olsen, M. Bernardini, B. Biskup, A. Boccardi,
                           T. Bogey, T. Bohl, C. Bracco, F. Braunmüller, S. Burger, G. Burt, S. Bustamante, B. Buttenschön,
                           A. Caldwell, M. Cascella, J. Chappell, E. Chevallay, M. Chung, D. Cooke, H. Damerau, L. Deacon,
                           L. H. Deubner, A. Dexter, S. Doebert, J. Farmer, V. N. Fedosseev, G. Fior, R. Fiorito,,4 R. A. Fonseca,
                           F. Friebel, L. Garolfi, S. Gessner, I. Gorgisyan, A. A. Gorn, E. Granados, O. Grulke, E. Gschwendtner,
                           A. Guerrero, J. Hansen, A. Helm, J. R. Henderson, C. Hessler, W. Hofle, M. Hüther, M. Ibison, L. Jensen,
                           S. Jolly, F. Keeble, S.-Y. Kim, F. Kraus, T. Lefevre, G. LeGodec, Y. Li, S. Liu, N. Lopes, K. V. Lotov,
                           L. Maricalva Brun, M. Martyanov,. Mazzoni, D. Medina Godoy, V. A. Minakov, J. Mitchell, J. C. Molendijk,
                           R. Mompo, J. T. Moody, M. Moreira, P. Muggli, E. Öz, E. Ozturk, C. Mutin, C. Pasquino, A. Pardons,
                           F. Peña Asmus, K. Pepitone, A. Perera, A. Petrenko, S. Pitman, G. Plyushchev, A. Pukhov, S. Rey,
                           K. Rieger, H. Ruhl, J. S. Schmidt, I. A. Shalimova, E. Shaposhnikova, P. Sherwood, L. O. Silva, L. Soby,
                           A. P. Sosedkin, R. Speroni, R. I. Spitsyn, P. V. Tuev, F. Velotti, L. Verra, V. A. Verzilov, J. Vieira,
                           H. Vincke, C. P. Welsch, B. Williamson, M. Wing, B. Woolley, G. Xia",
            "URL"      => "https://link.aps.org/doi/10.1103/PhysRevLett.122.054801",
            "PDF"      => "https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.122.054801",
            "DOI"      => "10.1103/PhysRevLett.122.054801",
            "Contrib"  => 2,
        ),
        "adli:2019" => array(
            "Type"     => "Article",
            "Date"     => "2019-02-08",
            "Title"    => "Experimental Observation of Proton Bunch Modulation in a Plasma at Varying Plasma Densities",
            "Journal"  => "Physical Review Letters",
            "Authors"  => "E. Adli, A. Ahuja, O. Apsimon, R. Apsimon, A.-M. Bachmann, D. Barrientos, M. M. Barros, J. Batkiewicz,
                           F. Batsch, J. Bauche, V. K. Berglyd Olsen, M. Bernardini, B. Biskup, A. Boccardi, T. Bogey, T. Bohl,
                           C. Bracco, F. Braunmüller, S. Burger, G. Burt, S. Bustamante, B. Buttenschön, A. Caldwell, M. Cascella,
                           J. Chappell, E. Chevallay, M. Chung, D. Cooke, H. Damerau, L. Deacon, L. H. Deubner, A. Dexter,
                           S. Doebert, J. Farmer, V. N. Fedosseev, G. Fior, R. Fiorito, R. A. Fonseca, F. Friebel, L. Garolfi,
                           S. Gessner, I. Gorgisyan, A. A. Gorn, E. Granados, O. Grulke, E. Gschwendtner, A. Guerrero, J. Hansen,
                           A. Helm, J. R. Henderson, C. Hessler, W. Hofle, M. Hüther, M. Ibison, L. Jensen, S. Jolly, F. Keeble,
                           S.-Y. Kim, F. Kraus, T. Lefevre, G. LeGodec, Y. Li, S. Liu, N. Lopes, K. V. Lotov, L. Maricalva Brun,
                           M. Martyanov, S. Mazzoni, D. Medina Godoy, V. A. Minakov, J. Mitchell, J. C. Molendijk, R. Mompo,
                           J. T. Moody, M. Moreira, P. Muggli, C. Mutin, E. Öz, E. Ozturk, C. Pasquino, A. Pardons, F. Peña Asmus,
                           K. Pepitone, A. Perera, A. Petrenko, S. Pitman, G. Plyushchev, A. Pukhov, S. Rey, K. Rieger, H. Ruhl,
                           J. S. Schmidt, I. A. Shalimova, E. Shaposhnikova, P. Sherwood, L. O. Silva, L. Soby, A. P. Sosedkin,
                           R. Speroni, R. I. Spitsyn, P. V. Tuev, M. Turner, F. Velotti, L. Verra, V. A. Verzilov, J. Vieira,
                           H. Vincke, C. P. Welsch, B. Williamson, M. Wing, B. Woolley, G. Xia",
            "URL"      => "https://link.aps.org/doi/10.1103/PhysRevLett.122.054802",
            "PDF"      => "https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.122.054802",
            "DOI"      => "10.1103/PhysRevLett.122.054802",
            "Contrib"  => 3,
        ),
        "adli:2018" => array(
            "Type"     => "Article",
            "Date"     => "2018-08-29",
            "Title"    => "Acceleration of electrons in the plasma wakefield of a proton bunch",
            "Journal"  => "Nature",
            "Authors"  => "E. Adli, A. Ahuja, O. Apsimon, R. Apsimon, A.-M. Bachmann, D. Barrientos, F. Batsch, J. Bauche,
                           V. K. Berglyd Olsen, M. Bernardini, T. Bohl, C. Bracco, F. Braunmüller, G. Burt, B. Buttenschön,
                           A. Caldwell, M. Cascella, J. Chappell, E. Chevallay, M. Chung, D. Cooke, H. Damerau, L. Deacon,
                           L. H. Deubner, A. Dexter, S. Doebert, J. Farmer, V. N. Fedosseev, R. Fiorito, R. A. Fonseca,
                           F. Friebel, L. Garolfi, S. Gessner, I. Gorgisyan, A. A. Gorn, E. Granados, O. Grulke,
                           E. Gschwendtner, J. Hansen, A. Helm, J. R. Henderson, M. Hüther, M. Ibison, L. Jensen, S. Jolly,
                           F. Keeble, S.-Y. Kim, F. Kraus, Y. Li, S. Liu, N. Lopes, K. V. Lotov, L. Maricalva Brun,
                           M. Martyanov, S. Mazzoni, D. Medina Godoy, V. A. Minakov, J. Mitchell, J. C. Molendijk,
                           J. T. Moody, M. Moreira, P. Muggli, E. Öz, C. Pasquino, A. Pardons, F. Peña Asmus, K. Pepitone,
                           A. Perera, A. Petrenko, S. Pitman, A. Pukhov, S. Rey, K. Rieger, H. Ruhl, J. S. Schmidt,
                           I. A. Shalimova, P. Sherwood, L. O. Silva, L. Soby, A. P. Sosedkin, R. Speroni, R. I. Spitsyn,
                           P. V. Tuev, M. Turner, F. Velotti, L. Verra, V. A. Verzilov, J. Vieira, C. P. Welsch,
                           B. Williamson, M. Wing, B. Woolley & G. Xia",
            "URL"      => "https://www.nature.com/articles/s41586-018-0485-4",
            "PDF"      => "https://www.nature.com/articles/s41586-018-0485-4_reference.pdf",
            "DOI"      => "10.1038/s41586-018-0485-4",
            "Contrib"  => 3,
        ),
        "sjobak:2018" => array(
            "Type"     => "Article",
            "Date"     => "2018-08-19",
            "Title"    => "Dynamic Simulations in SixTrack",
            "Journal"  => "arXiv and CERN",
            "Authors"  => "K. Sjobak, V.K. Berglyd Olsen, R. De Maria, M. Fitterer, A. Santamaría García, H. Garcia-Morales,
                           A. Mereghetti, J.F. Wagner, S.J. Wretborn",
            "URL"      => "http://arxiv.org/abs/1808.06248",
            "PrePrint" => "http://arxiv.org/abs/1808.06248",
            "Contrib"  => 2,
        ),
        "lindstrom:2018" => array(
            "Type"     => "Proceedings",
            "Date"     => "2018-04-29",
            "Title"    => "Crab Cavity Failures Combined with a Loss of the Beam-Beam Kick in the High Luminosity LHC",
            "Journal"  => "Proceedings of IPAC2018, Vancouver, BC, Canada",
            "Authors"  => "B. Lindstrom, H. Burkhardt, V.K.B. Olsen, A. Santamaría García, K.N. Sjobak, M. Valette, D. Wollmann",
            "URL"      => "http://ipac2018.vrws.de/html/mopmf.htm",
            "PDF"      => "http://jacow.org/ipac2018/papers/mopmf042.pdf",
            "DOI"      => "10.18429/JACoW-IPAC2018-MOPMF042",
            "Contrib"  => 3,
        ),
        "berglyd_olsen:2018" => array(
            "Type"     => "Article",
            "Date"     => "2018-01-16",
            "Title"    => "Emittance preservation of an electron beam in a loaded quasilinear plasma wakefield",
            "Journal"  => "Physical Review Accelerators and Beams",
            "Authors"  => "Veronica K. Berglyd Olsen, Erik Adli (University of Oslo, Oslo, Norway),
                           Patric Muggli (Max Planck Institute for Physics, Munich, Germany and CERN, Geneva, Switzerland).",
            "URL"      => "https://link.aps.org/doi/10.1103/PhysRevAccelBeams.21.011301",
            "PDF"      => "https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.21.011301",
            "DOI"      => "10.1103/PhysRevAccelBeams.21.011301",
            "PrePrint" => "https://arxiv.org/pdf/1710.04858.pdf",
            "Contrib"  => 1,
        ),
        "muggli:2017" => array(
            "Type"     => "Article",
            "Date"     => "2017-11-29",
            "Title"    => "AWAKE readiness for the study of the seeded self-modulation of a 400 GeV proton bunch",
            "Journal"  => "Plasma Physics and Controlled Fusion",
            "Authors"  => "P. Muggli, E. Adli, R. Apsimon, F. Asmus, R. Baartman, A.-M. Bachmann, M. Barros Marin,
                           F. Batsch, J. Bauche, V. K. Berglyd Olsen, M. Bernardini, B. Biskup, A. Boccardi, T. Bogey,
                           T. Bohl, C. Bracco, F. Braunmuller, S. Burger, G. Burt, S. Bustamante, B. Buttenschõn,
                           A. Butterworth, A. Caldwell, M. Cascella, E. Chevallay, M. Chung, H. Damerau, L. Deacon,
                           A. Dexter, P. Dirksen, S. Doebert, J. Farmer, V. Fedosseev, T. Feniet, G. Fior, R. Fiorito,
                           R. Fonseca, F. Friebel, P. Gander, S. Gessner, I. Gorgisyan, A. A. Gorn, O. Grulke,
                           E. Gschwendtner, A. Guerrero, J. Hansen, C. Hessler, W. Hofle, J. Holloway, M. H¨uther,
                           M. Ibison, M.R. Islam, L. Jensen, S. Jolly, M. Kasim, F. Keeble, S.-Y. Kim, F. Kraus,
                           A. Lasheen, T. Lefevre, G. LeGodec, Y. Li, S. Liu, N. Lopes, K. V. Lotov, M. Martyanov,
                           S. Mazzoni, D. Medina Godoy, O. Mete, V. A. Minakov, R. Mompo, J. Moody, M. T. Moreira,
                           J. Mitchell, C. Mutin, P. Norreys, E. Oz, E. Ozturk, W. Pauw, A. Pardons, C. Pasquino,
                           K. Pepitone, A. Petrenko, S. Pitmann, G. Plyushchev, A. Pukhov, K. Rieger, H. Ruhl,
                           J. Schmidt, I. A. Shalimova, E. Shaposhnikova, P. Sherwood, L. Silva, A. P. Sosedkin,
                           R. I. Spitsyn, K. Szczurek, J. Thomas, P. V. Tuev, M. Turner, V. Verzilov, J. Vieira,
                           H. Vincke, C. P. Welsch, B. Williamson, M. Wing, G. Xia, H. Zhang.",
            "URL"      => "http://iopscience.iop.org/article/10.1088/1361-6587/aa941c",
            "PDF"      => "http://iopscience.iop.org/article/10.1088/1361-6587/aa941c/pdf",
            "DOI"      => "10.1088/1361-6587/aa941c",
            "Contrib"  => 3,
        ),
        "berglyd_olsen:2017" => array(
            "Type"     => "Proceedings",
            "Date"     => "2017-06-19",
            "Title"    => "Data Acquisition and Controls Integration of the AWAKE Experiment at CERN",
            "Journal"  => "Proceedings of IPAC2017, Copenhagen, Denmark",
            "Authors"  => "Veronica K. Berglyd Olsen (University of Oslo, Oslo, Norway), Jozef J. Batkiewicz,
                           Stephane Deghaye, Spencer J. Gessner, Edda Gschwendtner (CERN, Geneva, Switzerland),
                           Patric Muggli (Max Planck Institute for Physics, Munich, Germany and CERN, Geneva, Switzerland).<br>
                           <i><b>Note: The published PDF is broken. The PDF link below links to a working version.</b></i>",
            "URL"      => "http://accelconf.web.cern.ch/AccelConf/ipac2017/doi/JACoW-IPAC2017-TUPIK061.html",
            "PDF"      => "http://vkbo.net/files/IPAC17-TUPIK061.pdf",
            "DOI"      => "10.18429/JACoW-IPAC2017-TUPIK061",
            "Contrib"  => 1,
        ),
        "berglyd_olsen:2016a" => array(
            "Type"     => "Proceedings",
            "Date"     => "2016-10-11",
            "Title"    => "Loading of Wakefields in a Plasma Accelerator Section Driven by a Self-Modulated Proton Beam",
            "Journal"  => "Proceedings of NAPAC16, Chicago, IL, USA – w/Contributing Talk",
            "Authors"  => "V. K. Berglyd Olsen, E. Adli (University of Oslo, Oslo, Norway),
                           P. Muggli (Max Planck Institute for Physics, Munich, Germany and CERN, Geneva, Switzerland),
                           J. M. Vieira (Instituto Superior Technico, Lisbon, Portugal)",
            "URL"      => "http://accelconf.web.cern.ch/AccelConf/napac2016/doi/JACoW-NAPAC2016-TUA4CO03.html",
            "PDF"      => "http://accelconf.web.cern.ch/AccelConf/napac2016/papers/tua4co03.pdf",
            "Slides"   => "http://accelconf.web.cern.ch/AccelConf/napac2016/talks/tua4co03_talk.pdf",
            "DOI"      => "10.18429/JACoW-NAPAC2016-TUA4CO03",
            "Contrib"  => 1,
        ),
        "gschwendtner:2016" => array(
            "Type"     => "Article",
            "Date"     => "2016-09-01",
            "Title"    => "AWAKE, The Advanced Proton Driven Plasma Wakefield Acceleration Experiment at CERN",
            "Journal"  => "Nuclear Instruments and Methods in Physics Research Section A",
            "JrnTopic" => "Accelerators, Spectrometers, Detectors and Associated Equipment",
            "Volume"   => "829",
            "Authors"  => "E. Gschwendtner, E. Adli, L. Amorim, R. Apsimon, R. Assmann, A.-M. Bachmann, F. Batsch,
                           J. Bauche, V.K. Berglyd Olsen, M. Bernardini, R. Bingham, B. Biskup, T. Bohl, C. Bracco,
                           P. N. Burrows, G. Burt, B. Buttenschon, A. Butterworth, A. Caldwell, M. Cascella,
                           E. Chevallay, S. Cipiccia, H. Damerau, L. Deacon, P. Dirksen, S. Doebert, U. Dorda,
                           J. Farmer, V. Fedosseev, E. Feldbaumer, R. Fiorito, R. Fonseca, F. Friebel, A.A. Gorn,
                           O. Grulke, J. Hansen, C. Hessler, W. Hofle, J. Holloway, M. Huther, D. Jaroszynski,
                           L. Jensen, S. Jolly, A. Joulaei, M. Kasim, F. Keeble, Y. Li, S. Liu, N. Lopes, K.V. Lotov,
                           S. Mandry, R. Martorelli, M. Martyanov, S. Mazzoni, O. Mete, V.A. Minakov, J. Mitchell,
                           J. Moody, P. Muggli, Z. Najmudin, P. Norreys, E. Oz, A. Pardons, K. Pepitone, A. Petrenko,
                           G. Plyushchev, A. Pukhov, K. Rieger, H. Ruhl, F. Salveter, N. Savard, J. Schmidt, A. Seryi,
                           E. Shaposhnikova, Z.M. Sheng, P. Sherwood, L. Silva, L. Soby, A.P. Sosedkin, R.I. Spitsyn,
                           R. Trines, P.V. Tuev, M. Turner, V. Verzilov, J. Vieira, H. Vincke, Y. Wei, C.P. Welsch,
                           M. Wing, G. Xia, H. Zhang",
            "URL"      => "http://www.sciencedirect.com/science/article/pii/S0168900216001881",
            "PrePrint" => "http://arxiv.org/abs/1512.05498",
            "DOI"      => "10.1016/j.nima.2016.02.026",
            "Contrib"  => 3,
        ),
        "caldwell:2016" => array(
            "Type"     => "Article",
            "Date"     => "2016-09-01",
            "Title"    => "Path to AWAKE: Evolution of the concept",
            "Journal"  => "Nuclear Instruments and Methods in Physics Research Section A",
            "JrnTopic" => "Accelerators, Spectrometers, Detectors and Associated Equipment",
            "Volume"   => "829",
            "Authors"  => "A. Caldwell, E. Adli, L. Amorim, R. Apsimon, T. Argyropoulos, R. Assmann, A.M. Bachmann,
                           F. Batsch, J. Bauche, V.K. Berglyd Olsen, M. Bernardini, R. Bingham, B. Biskup, T. Bohl,
                           C. Bracco, P.N. Burrows, G. Burt, B. Buttenschon, A. Butterworth, M. Cascella,
                           S. Chattopadhyay, E. Chevallay, S. Cipiccia, H. Damerau, L. Deacon, P. Dirksen, S. Doebert,
                           U. Dorda, E. Elsen, J. Farmer, S. Fartoukh, V. Fedosseev, E. Feldbaumer, R. Fiorito,
                           R. Fonseca, F. Friebel, G. Geschonke, B. Goddard, A.A. Gorn, O. Grulke, E. Gschwendtner,
                           J. Hansen, C. Hessler, S. Hillenbrand, W. Hofle, J. Holloway, C. Huang, M. Huther,
                           D. Jaroszynski, L. Jensen, S. Jolly, A. Joulaei, M. Kasim, F. Keeble, R. Kersevan, N. Kumar,
                           Y. Li, S. Liu, N. Lopes, K.V. Lotov, W. Lu, J. Machacek, S. Mandry, I. Martin, R. Martorelli,
                           M. Martyanov, S. Mazzoni, M. Meddahi, L. Merminga, O. Mete, V.A. Minakov, J. Mitchell,
                           J. Moody, A.S. Muller, Z. Najmudin, T.C.Q. Noakes, P. Norreys, J. Osterhoff, E. Oz,
                           A. Pardons, K. Pepitone, A. Petrenko, G. Plyushchev, J. Pozimski, A. Pukhov, O. Reimann,
                           K. Rieger, S. Roesler, H. Ruhl, T. Rusnak, F. Salveter, N. Savard, J. Schmidt,
                           H. von der Schmitt, A. Seryi, E. Shaposhnikova, Z.M. Sheng, P. Sherwood, L. Silva, F. Simon,
                           L. Soby, A.P. Sosedkin, R.I. Spitsyn, T. Tajima, R. Tarkeshian, H. Timko, R. Trines,
                           T. Tueckmantel, P.V. Tuev, M. Turner, F. Velotti, V. Verzilov, J. Vieira, H. Vincke, Y. Wei,
                           C.P. Welsch, M. Wing, G. Xia, V. Yakimenko, H. Zhang, F. Zimmermann",
            "URL"      => "http://www.sciencedirect.com/science/article/pii/S0168900215016307",
            "PrePrint" => "http://arxiv.org/abs/1511.09032",
            "DOI"      => "10.1016/j.nima.2015.12.050",
            "Contrib"  => 3,
        ),
        "adli:2016" => array(
            "Type"     => "Article",
            "Date"     => "2016-09-01",
            "Title"    => "Progress of plasma wakefield self-modulation experiments at FACET",
            "Journal"  => "Nuclear Instruments and Methods in Physics Research Section A",
            "JrnTopic" => "Accelerators, Spectrometers, Detectors and Associated Equipment",
            "Volume"   => "829",
            "Authors"  => "E. Adli, V.K. Berglyd Olsen, C.A. Lindstrøm, P. Muggli, O. Reimann, J.M. Vieira,
                           L.D. Amorim, C.I. Clarke, S.J. Gessner, S.Z. Green, M.J. Hogan, M.D. Litos, B.D. O׳Shea,
                           V. Yakimenko, C. Clayton, K.A. Marsh, W.B. Mori, C. Joshi, N. Vafaei-Najafabadi,
                           O. Williams",
            "URL"      => "http://www.sciencedirect.com/science/article/pii/S0168900216002515",
            "DOI"      => "10.1016/j.nima.2016.02.075",
            "Contrib"  => 2,
        ),
        "muggli:2015" => array(
            "Type"     => "Proceedings",
            "Date"     => "2015-05-08",
            "Title"    => "Measuring the Self-modulation Instability of Electron and Positron Bunches in Plasmas",
            "Journal"  => "Proceedings of IPAC2015, Richmond, Virginia, USA",
            "Authors"  => "P. Muggli, O. Reimann (MPI-P, München, Germany), E. Adli,
                           V.K. Berglyd Olsen (University of Oslo, Oslo, Norway), J. Allen, S.J. Gessner, S.Z. Green,
                           M.J. Hogan, M.D. Litos (SLAC, Menlo Park, California, USA),
                           L.D. Amorim (IST, Lisboa, Portugal), G. Andonian, C. Joshi, K.A. Marsh, W.B. Mori,
                           B.D. O'Shea, N. Vafaei-Najafabadi, O. Williams (UCLA, Los Angeles, California, USA),
                           N.C. Lopes, L.O. Silva, J. Vieira (Instituto Superior Tecnico, Lisbon, Portugal)",
            "URL"      => "http://inspirehep.net/record/1417872",
            "PDF"      => "https://jacowfs.jlab.org/conf/proceedings/IPAC2015/papers/wepwa008.pdf",
            "Contrib"  => 3,
        ),
        "berglyd_olsen:2015" => array(
            "Type"     => "Proceedings",
            "Date"     => "2015-05-08",
            "Title"    => "Loading of a plasma-wakefield accelerator section driven by a self-modulated proton bunch",
            "Journal"  => "Proceedings of IPAC2015, Richmond, Virginia, USA",
            "Authors"  => "Veronica K. Berglyd Olsen, Erik Adli (University of Oslo, Oslo),
                           Patric Muggli (MPI, Muenchen), Ligia Diana Amorim,
                           Jorge Miguel Vieira (Instituto Superior Tecnico, Lisbon)",
            "URL"      => "http://inspirehep.net/record/1417886",
            "PDF"      => "https://jacowfs.jlab.org/conf/proceedings/IPAC2015/papers/wepwa026.pdf",
            "Contrib"  => 1,
        ),
        "muggli:2014" => array(
            "Type"     => "Proceedings",
            "Date"     => "2014-06-17",
            "Title"    => "Electron Bunch Self-modulation in Long Plasmas at SLAC FACET",
            "Journal"  => "Proceedings of IPAC2014, Dresden, Germany",
            "Authors"  => "Patric Muggli, Olaf Reimann (MPI, Muenchen), Ligia Diana Amorim, Nelson Carreira Lopes,
                           Jorge Miguel Vieira (Instituto Superior Tecnico, Lisbon), Spencer Jake Gessner, Mark Hogan,
                           Selina Zhao Li, Michael Dennis Litos (SLAC, Menlo Park, California), Chan Joshi,
                           Kenneth Marsh, Warren Mori, Navid Vafaei-Najafabadi (UCLA, Los Angeles, California),
                           Erik Adli, Veronica K. Berglyd Olsen (University of Oslo, Oslo)",
            "URL"      => "https://inspirehep.net/record/1313831",
            "PDF"      => "http://jacow.org/IPAC2014/papers/tupme050.pdf",
            "Contrib"  => 3,
        ),
        "berglyd_olsen:2012" => array(
            "Type"     => "Thesis",
            "Date"     => "2012-12-03",
            "Title"    => "Full Configuration Interaction Simulation of Quantum Dots",
            "Journal"  => "Thesis submitted for the degree of Master of Science, University of Oslo",
            "Authors"  => "Veronica K. Berglyd Olsen, University of Oslo.
                           Thesis advisor: Morten Hjorth-Jensen, University of Oslo and Michigan State University.",
            "URL"      => "https://www.duo.uio.no/handle/123456789/34217",
            "PDF"      => "https://www.duo.uio.no/bitstream/handle/10852/34217/vkb-olsen.pdf",
            "Contrib"  => 1,
        ),
    );

?>
